### ISSUE TITLE
Not posting all the new posts needs a way to store the posts that happen in between the 5 minute interval

### ISSUE THREAD

**Issue by jpmi1** [AlJohri/RedditSync#2]
https://nimbus.everhelper.me/client/notes/share/390209/fooe5c05qfebpddari5l Posts
https://nimbus.everhelper.me/client/notes/share/390210/ekfipcgieidsdv0u0c16 should not miss the 4 or 5 posts.

**Comment by AlJohri** [comment]
I haven't looked at the screenshots here but you might just want to decrease the interval? I haven't checked Reddit's API limits though.

**Comment by jpmi1** [comment]
Temporary fix has been added with checking every 30 seconds for a post
